version: "2"
services:
  web:
    build: .
    environment:
      PYDIO_MYSQL_USER: pydio
      PYDIO_MYSQL_PASSWORD: pydio
      PYDIO_MYSQL_DATABASE: pydio
      PYDIO_MYSQL_HOST: mysql
    labels:
      - traefik.frontend.rule=Host:pydio.docker
    volumes:
      - ./var/data/pydio/run:/var/run/pydio
      - ./var/data/pydio/lib:/var/lib/pydio
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pydio
      MYSQL_USER: pydio
      MYSQL_PASSWORD: pydio
      MYSQL_DATABASE: pydio
    volumes:
      - ./var/data/mysql:/var/lib/mysql
